### ISSUE TITLE
Usean kommenttikentän lisääminen kerralla

### ISSUE THREAD

**Issue by lococco** [hrmJ/lhportal#4]
Kun luo samalla kerralla useita kommentinlisäyskenttiä, niin ensimmäisen lisäyksessä tulokseksi tulee tyhjä kommentti. (ainakin googlen selaimella)

**Comment by hrmJ** [comment]
Usean kommentin luominen kerralla on oikeastaan bugi, ei ehkä ihan toivottavaa käyttäytymistä.. Korjasin nyt niin, että jos klikkaa uudestaan "lisää kommentti", mitään ei tapahdu, vaan kerralla voi luoda vain yhden kommentin
